<?php

/**
 * @file
 * Contains teleprompter.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function teleprompter_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the teleprompter module.
    case 'help.page.teleprompter':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Simple headless Teleprompter Service') . '</p>';
      return $output;

    default:
  }
}
